### ISSUE TITLE
Coincidence, je ne crois pas

### ISSUE THREAD

**Issue by Evenfire** [bertrandda/par-ici-tennis#3]
Did you get a notification or something when I pulled your code? AFAIK, there is no hook on 'clone'.
I just "fixed" the captcha to test the script locally. Like 40 minutes ago. Incredible timing
🤯

**Comment by bertrandda** [comment]
Sorry for bad timing, I learnt about CAPTCHA on saturday, fix it on sunday evening and launch it several time on monday to test it. Next time I'll push it directly to avoid doing the job twice.
For rest of the script, if you have other improvements feel free to open PR, any help is welcome.
Glad to see that this script interests someone.

**Comment by Evenfire** [comment]
No worries, I was just surprised by the synchronization. Especially since there had been no commit on master for several month.
